[profile.default]
src = "contracts/src"
out = "contracts/foundry/out"
libs = ["node_modules", "contracts/foundry/lib"]
cache_path = "contracts/foundry/cache"
test = "contracts/foundry/test"
optimizer = true
optimizer_runs = 200

[fuzz]
runs = 10000

[invariant]
runs = 10000
depth = 50